# Generated by Django 5.0.6 on 2026-06-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProceso',
            fields=[
                ('identificador', models.IntegerField(db_column='Identificador', primary_key=True, serialize=False)),
                ('tipo_proceso', models.CharField(blank=True, db_column='Tipo_Proceso', max_length=50, null=True)),
                ('nombre_proceso', models.CharField(blank=True, db_column='Nombre_Proceso', max_length=500, null=True)),
                ('orden_consecutivo', models.IntegerField(blank=True, db_column='Orden_Consecutivo', default=0, null=True)),
            ],
            options={
                'db_table': 'base_proceso',
                'managed': False,
            },
        ),
    ]
