# Generated by Django 5.0.6 on 2026-06-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MejCronograma',
            fields=[
                ('id_crono', models.IntegerField(primary_key=True, serialize=False)),
                ('id_proceso', models.IntegerField()),
                ('semana', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('fin', models.CharField(blank=True, max_length=20, null=True)),
                ('planificado', models.FloatField(blank=True, null=True)),
                ('logrado', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mej_cronograma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mejora',
            fields=[
                ('id_mejora', models.IntegerField(primary_key=True, serialize=False)),
                ('id_proceso', models.IntegerField(unique=True)),
                ('codigo_proceso', models.CharField(blank=True, max_length=100, null=True)),
                ('proyecto', models.CharField(blank=True, max_length=500, null=True)),
                ('codigo_proyecto', models.CharField(blank=True, max_length=100, null=True)),
                ('proceso_asociado', models.CharField(blank=True, max_length=500, null=True)),
                ('responsable_proceso', models.CharField(blank=True, max_length=300, null=True)),
                ('responsable_proyecto', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_solicitud', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_requerida', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_mejora', models.CharField(blank=True, max_length=100, null=True)),
                ('importancia', models.CharField(blank=True, max_length=100, null=True)),
                ('complejidad', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_oportunidad', models.CharField(blank=True, max_length=100, null=True)),
                ('oportunidades_identificadas', models.TextField(blank=True, null=True)),
                ('consecuencias_marcadas', models.JSONField(blank=True, null=True)),
                ('evaluaciones_json', models.JSONField(blank=True, null=True)),
                ('confianza_json', models.JSONField(blank=True, null=True)),
                ('acciones_json', models.JSONField(blank=True, null=True)),
                ('costo_valor', models.FloatField(blank=True, null=True)),
                ('costo_nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('impacto_valor', models.FloatField(blank=True, null=True)),
                ('impacto_nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('factibilidad_valor', models.FloatField(blank=True, null=True)),
                ('factibilidad_nivel', models.CharField(blank=True, max_length=50, null=True)),
                ('factibilidad_accion', models.CharField(blank=True, max_length=300, null=True)),
                ('plazo_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('plazo_fin', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('desc_problema', models.TextField(blank=True, null=True)),
                ('desc_objetivo', models.TextField(blank=True, null=True)),
                ('desc_indicador_meta', models.TextField(blank=True, null=True)),
                ('desc_alcance', models.TextField(blank=True, null=True)),
                ('desc_accion_mejora', models.TextField(blank=True, null=True)),
                ('desc_impacto', models.TextField(blank=True, null=True)),
                ('cronograma_json', models.JSONField(blank=True, null=True)),
                ('cronograma_proceso_json', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mejora',
                'managed': False,
            },
        ),
    ]
