# Generated by Django 5.0.6 on 2026-06-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSCausaIshikawa',
            fields=[
                ('id_causa', models.IntegerField(primary_key=True, serialize=False)),
                ('id_def', models.IntegerField()),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('causa', models.TextField(blank=True, null=True)),
                ('subcausa', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('proceso_relacionado', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_registro', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ss_causas_ishikawa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SSCincoPorques',
            fields=[
                ('id_porq', models.IntegerField(primary_key=True, serialize=False)),
                ('id_def', models.IntegerField()),
                ('problema', models.TextField(blank=True, null=True)),
                ('por1', models.TextField(blank=True, null=True)),
                ('resp1', models.TextField(blank=True, null=True)),
                ('por2', models.TextField(blank=True, null=True)),
                ('resp2', models.TextField(blank=True, null=True)),
                ('por3', models.TextField(blank=True, null=True)),
                ('resp3', models.TextField(blank=True, null=True)),
                ('por4', models.TextField(blank=True, null=True)),
                ('resp4', models.TextField(blank=True, null=True)),
                ('por5', models.TextField(blank=True, null=True)),
                ('resp5', models.TextField(blank=True, null=True)),
                ('causa_raiz', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ss_cinco_porques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SSControl',
            fields=[
                ('id_ctrl', models.IntegerField(primary_key=True, serialize=False)),
                ('id_def', models.IntegerField()),
                ('que_controlar', models.TextField(blank=True, null=True)),
                ('como_medir', models.TextField(blank=True, null=True)),
                ('limite_superior', models.CharField(blank=True, max_length=50, null=True)),
                ('limite_central', models.CharField(blank=True, max_length=50, null=True)),
                ('limite_inferior', models.CharField(blank=True, max_length=50, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=100, null=True)),
                ('responsable', models.CharField(blank=True, max_length=300, null=True)),
                ('registro', models.CharField(blank=True, max_length=300, null=True)),
                ('accion_correctiva', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ss_control',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SSDefinicion',
            fields=[
                ('id_def', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_proceso', models.CharField(blank=True, max_length=500, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('indicador', models.CharField(blank=True, max_length=200, null=True)),
                ('meta', models.FloatField(blank=True, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo_indicador', models.CharField(blank=True, max_length=100, null=True)),
                ('definicion_defecto', models.TextField(blank=True, null=True)),
                ('oportunidades_defecto', models.FloatField(blank=True, default=1, null=True)),
                ('fecha_creacion', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.CharField(default='activo', max_length=30)),
            ],
            options={
                'db_table': 'ss_definicion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SSHistorico',
            fields=[
                ('id_hist', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_hora', models.CharField(blank=True, max_length=30, null=True)),
                ('proceso', models.CharField(blank=True, max_length=500, null=True)),
                ('fase_dmaic', models.CharField(blank=True, max_length=50, null=True)),
                ('accion', models.CharField(blank=True, max_length=200, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ss_historico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SSMedicion',
            fields=[
                ('id_med', models.IntegerField(primary_key=True, serialize=False)),
                ('id_def', models.IntegerField()),
                ('periodo', models.CharField(blank=True, max_length=100, null=True)),
                ('unidades_evaluadas', models.FloatField(blank=True, null=True)),
                ('defectos', models.FloatField(blank=True, null=True)),
                ('yield_pct', models.FloatField(blank=True, null=True)),
                ('dpmo', models.FloatField(blank=True, null=True)),
                ('nivel_sigma', models.FloatField(blank=True, null=True)),
                ('cumplimiento', models.FloatField(blank=True, null=True)),
                ('fecha_registro', models.CharField(blank=True, max_length=30, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'ss_mediciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SSMejora',
            fields=[
                ('id_mej', models.IntegerField(primary_key=True, serialize=False)),
                ('id_def', models.IntegerField()),
                ('id_causa', models.IntegerField(blank=True, null=True)),
                ('problema_encontrado', models.TextField(blank=True, null=True)),
                ('accion_propuesta', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('sigma_antes', models.FloatField(blank=True, null=True)),
                ('sigma_despues', models.FloatField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ss_mejoras',
                'managed': False,
            },
        ),
    ]
