# Generated by Django 5.0.6 on 2026-06-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoProceso',
            fields=[
                ('id_proceso', models.IntegerField(primary_key=True, serialize=False)),
                ('estado', models.CharField(default='en_ejecucion', max_length=20)),
            ],
            options={
                'db_table': 'estado_proceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndAccion',
            fields=[
                ('id_accion', models.IntegerField(primary_key=True, serialize=False)),
                ('id_objetivo', models.IntegerField()),
                ('id_indicador', models.IntegerField()),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('indicador_texto', models.TextField(blank=True, null=True)),
                ('especifico', models.TextField(blank=True, null=True)),
                ('relevante', models.TextField(blank=True, null=True)),
                ('medible', models.TextField(blank=True, null=True)),
                ('realizable', models.TextField(blank=True, null=True)),
                ('temporal', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ind_accion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndAvance',
            fields=[
                ('id_avance', models.IntegerField(primary_key=True, serialize=False)),
                ('id_indicador', models.IntegerField()),
                ('periodo', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_real', models.FloatField(blank=True, null=True)),
                ('fecha_registro', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ind_avance',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndConfig',
            fields=[
                ('clave', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('valor', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ind_config',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id_indicador', models.IntegerField(primary_key=True, serialize=False)),
                ('id_proceso', models.IntegerField()),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_indicador', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('justificacion', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(blank=True, max_length=300, null=True)),
                ('metodo_calculo', models.TextField(blank=True, null=True)),
                ('sentido_esperado', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=100, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=50, null=True)),
                ('fuente_datos', models.CharField(blank=True, max_length=300, null=True)),
                ('periodicidad', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_fin', models.CharField(blank=True, max_length=20, null=True)),
                ('meta_final', models.FloatField(blank=True, null=True)),
                ('tipo_agregacion', models.CharField(blank=True, max_length=100, null=True)),
                ('relevancia', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'indicador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndLogro',
            fields=[
                ('id_logro', models.IntegerField(primary_key=True, serialize=False)),
                ('id_indicador', models.IntegerField()),
                ('periodo', models.CharField(blank=True, max_length=100, null=True)),
                ('es_linea_base', models.BooleanField(default=False)),
                ('valor_planificado', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ind_logro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndObjetivo',
            fields=[
                ('id_objetivo', models.IntegerField(primary_key=True, serialize=False)),
                ('id_indicador', models.IntegerField()),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('indicador_texto', models.TextField(blank=True, null=True)),
                ('especifico', models.TextField(blank=True, null=True)),
                ('relevante', models.TextField(blank=True, null=True)),
                ('medible', models.TextField(blank=True, null=True)),
                ('realizable', models.TextField(blank=True, null=True)),
                ('temporal', models.TextField(blank=True, null=True)),
                ('prioridad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ind_objetivo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IndRango',
            fields=[
                ('id_rango', models.IntegerField(primary_key=True, serialize=False)),
                ('id_indicador', models.IntegerField()),
                ('etiqueta', models.CharField(blank=True, max_length=200, null=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('desde', models.FloatField(blank=True, null=True)),
                ('hasta', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ind_rango',
                'managed': False,
            },
        ),
    ]
