# Generated by Django 5.0.6 on 2026-06-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FichaActividad',
            fields=[
                ('id_actividad', models.IntegerField(primary_key=True, serialize=False)),
                ('id_proceso', models.IntegerField()),
                ('orden_secuencia', models.IntegerField(blank=True, null=True)),
                ('descripcion_actividad', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ficha_actividad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaFlujoSipoc',
            fields=[
                ('id_flujo', models.IntegerField(primary_key=True, serialize=False)),
                ('id_proceso', models.IntegerField()),
                ('proveedor', models.TextField(blank=True, null=True)),
                ('elemento_entrada', models.TextField(blank=True, null=True)),
                ('producto', models.TextField(blank=True, null=True)),
                ('receptor', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ficha_flujo_sipoc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaProceso',
            fields=[
                ('id_proceso', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_proceso', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo_proceso', models.CharField(blank=True, max_length=50, null=True)),
                ('dueno_proceso', models.CharField(blank=True, max_length=300, null=True)),
                ('objetivo_general', models.TextField(blank=True, null=True)),
                ('objetivo_estrategico', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ficha_proceso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaRegistro',
            fields=[
                ('id_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('id_proceso', models.IntegerField()),
                ('nombre_titulo', models.CharField(blank=True, max_length=500, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ficha_registro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FichaRiesgo',
            fields=[
                ('id_riesgo', models.IntegerField(primary_key=True, serialize=False)),
                ('id_proceso', models.IntegerField()),
                ('descripcion_riesgo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ficha_riesgo',
                'managed': False,
            },
        ),
    ]
