# Generated by Django 5.0.6 on 2026-06-25 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas_procesos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagramaDrawio',
            fields=[
                ('id_proceso', models.IntegerField(primary_key=True, serialize=False)),
                ('xml', models.TextField(blank=True, null=True)),
                ('svg', models.TextField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'diagrama_drawio',
            },
        ),
    ]
