# Generated by Django 5.0.6 on 2026-06-27 04:01

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=256)),
                ('nombre_completo', models.CharField(blank=True, default='', max_length=200)),
                ('organizacion', models.CharField(blank=True, default='', max_length=200)),
                ('rol', models.CharField(default='admin', max_length=20)),
                ('token', models.CharField(default=secrets.token_urlsafe, max_length=64, unique=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_solicitud_registro',
            },
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'managed': False},
        ),
    ]
